server:
  port: 8989

management:
  port: 8990

info:
  component: turbine-server


logging:
  level:
    root: INFO
    com.netflix.discovery: INFO

    # Get info regarding connection to the cofig server and retries if required
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG

    # org.springframework.integration: DEBUG

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO

turbine:
  aggregator:
    clusterConfig: GREETING
  appConfig: greeting-service
  clusterNameExpression: appGroupName

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

