server:
  port: 9003

management:
  port: 9004

info:
  component: turbine

turbine:
  appConfig: greetingservice,greeterservice,profileservice,edgeserver
  clusterNameExpression: new String("default")
  combineHostPort: true



