server:
  port: 9010
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: letmein
#    key-password: changeme
#    key-alias: velware-dev-key
  contextPath: /uaa

info:
  component: authserver

security:
  user:
    password: password
#  oauth2:
#    client:
#      clientId: velware
#      clientSecret: velwareSecret
#      authorized-grant-types: authorization_code,refresh_token,implicit,password,client_credentials
#      scope: webshop
#      id: velware

logging:
  level:
    org.springframework.security: DEBUG