server:
  port: 9001

spring:
  rabbitmq:
    host: localhost
    port: 5672
  profiles:
    include: native
# Configuration of a local Git-repo for development locally without Docker
# note that we are still using git; We just access the git-repo via file: protocol
#spring.cloud.config.server.git.uri: file://../config-repository/
spring.cloud.config.server.native.searchLocations: classpath:/config-repository