spring.rabbitmq:
  host: localhost
  port: 5672

logging:
  level:
    root: INFO
    com.velware: INFO

    com.netflix.hystrix.contrib.javanica.command.GenericCommand: ERROR

    # Get info on failed OAuth access token validations
    org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoTokenServices: INFO

    # Get info regarding connection to the cofig server and retries if required
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO

    # Set DEBUG level on Hystrix to get an error message when a fallback method is used.
    com.netflix.hystrix: DEBUG
    com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedArchaiusProperty: WARN


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    instanceId: ${spring.application.name}:${random.value}
          #instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
        #instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
#    registryFetchIntervalSeconds: 1
#    instanceInfoReplicationIntervalSeconds: 1
#    initialInstanceInfoReplicationIntervalSeconds: 1
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://127.0.0.1:9002/eureka/



